export const COMPONENT_LABELS: Record<string, string> = {
  Problem: '📄 Problem',
  SingleSolutionGenerationComponent: '🧪 Single Solution Generation Component',
  PopulationGenerationComponent: '👥 Population Generation Component',
  SelectionComponent: '🎯 Selection Component',
  CrossoverComponent: '🧬 Crossover Component',
  MutationComponent: '🧫 Mutation Component',
  LocalSearchComponent: '🔍 Local Search Component',
  PerturbationComponent: '🌪️ Perturbation Component',
  TemperatureAcceptanceComponent: '🌡️ Temperature Acceptance Component',
  ReduceTemperatureComponent: '❄️ Reduce Temperature Component',
  ChangeNeighbourhoodComponent: '🧭 Change Neighbourhood Component',
  NeighbourhoodComponent: '🧩 Neighbourhood Component',
  SubstractionComponent: '➖ Substraction Component',
  SelectionOfBestComponent: '🏆 Selection of Best Component',
  StorageComponent: '📦 Storage Component',
  LoopComponent: '🔁 Loop Component',
  AcceptanceComponent: '✅ Acceptance Component',
};
